name: Build and Publish ASP.NET Core 8 App

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -c Release -o ./publish

      - name: Publish to GitHub Pages
        uses: gh-pages/publish@v1
        with:
          folder: ./publish
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Azure Web App (optional)
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-app-name>
          slot-name: <your-slot-name>
          publish-profile: <your-publish-profile>
          package: ./publish
