name: .NET Core 8 Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build project
        run: dotnet build -c Release

      - name: Run tests
        run: dotnet test -c Release

      - name: Publish project
        run: dotnet publish -c Release -o ./publish
